### ISSUE TITLE
Starting server on 0.0.0.0 instead of localhost

### ISSUE THREAD

**Issue by alayek** [feross/bittorrent-tracker#114]
Hi,

I am not able to start the server on 0.0.0.0. I don't want to run it on localhost. Instead, I wish to run it on 0.0.0.0, so that other devices connected to same local network can seed torrents. 

I run the following on my terminal:

```
$ bittorrent-tracker 0.0.0.0:8000
```
But, it keeps starting as 

```
HTTP tracker: http://localhost:8000/announce
UDP tracker: udp://localhost:8000
WebSocket tracker: ws://localhost:8000
```
Sorry if this is not an issue. But I couldn't find anything related to this in the docs or code-examples.

Kindly help me out here.  Thanks in advance.

**Comment by feross** [comment]
This is possible from the node.js API, but it wasn't exposed to the command line.

Just released a new version of `bittorrent-tracker` (7.2.0) with the options exposed:

```
$ bittorrent-tracker --http-hostname 0.0.0.0 --port 8000
```

There are three options total:

```
        --http-hostname [string]  change the http server hostname [default: '::']
        --udp-hostname [string]   change the udp hostname [default: '0.0.0.0']
        --udp6-hostname [string]  change the udp6 hostname [default: '::']
```

**Comment by feross** [comment]
Fixed in https://github.com/feross/bittorrent-tracker/commit/a240724bd24ef9142fa85b54922cbd3e0432aec2

**Comment by alayek** [comment]
Thanks @feross !
