### ISSUE TITLE
Using bittorrent-tracker from the browser

### ISSUE THREAD

**Issue by marcu87** [feross/bittorrent-tracker#130]
Hello, I'm triying to use the bittorrent-tracker from the browser; my goal is to get the peers count from a list of webtorrents.

To achieve this, I'm using webpack (if you have another better solution, I'll listen, I'm really new with all this), so I did: 

`webpack index.js index_bin.js`

Then I copied / pasted the example of the README, and did a little modification (using the magnet instead of a torrent file):

https://gist.github.com/marcu87/70f0129e6652c9b3316c

And the problem is... nothing happens.

It never uses the: client.on, client.once, client.on('scrape',... nothing... 0 logs in my console.

Then I changed my magnet link, and I added some sources: 

`magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%...`

And my console logs shows: 

`WebSocket connection to 'wss://tracker.btorrent.xyz/' failed: WebSocket is closed before the connection is established.
index_bin.js:10642 WebSocket connection to 'wss://tracker.fastcast.nz/' failed: WebSocket is closed before the connection is established.
index_bin.js:10642 WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: WebSocket is closed before the connection is established.
index_bin.js:10642 WebSocket connection to 'wss://tracker.webtorrent.io/' failed: WebSocket is closed before the connection is established.
testing.js:4 hola
index_bin.js:88 Unsupported tracker protocol: udp://exodus.desync.com:6969
index_bin.js:88 Unsupported tracker protocol: udp://tracker.coppersurfer.tk:6969
index_bin.js:88 Unsupported tracker protocol: udp://tracker.internetwarriors.net:1337
index_bin.js:88 Unsupported tracker protocol: udp://tracker.leechers-paradise.org:6969
index_bin.js:88 Unsupported tracker protocol: udp://tracker.openbittorrent.com:80`

Why my client is not connecting with the trackers, and why, even if there are no trackers, my client is not conneting with any peers? (My magnet link have peers, is the video used in the http://www.webtorrent.io/ home)

Thanks for the help

**Comment by feross** [comment]
For starters, you should not set the `wrtc` option unless you're trying to override the WebRTC implementation that is use. Remove [this line](https://gist.github.com/marcu87/70f0129e6652c9b3316c#file-gistfile1-txt-L20).

**Comment by feross** [comment]
I don't use `webpack` and think it's more complicated that necessary. Here's a full example with `browserify`.

```
npm install browserify parse-torrent bittorrent-tracker
```

`scrape.js`:

```js
var Tracker = require('bittorrent-tracker')
var magnet = require('magnet-uri')

// These values don't matter
var peerId = new Buffer('01234567890123456789')
var port = 6889

var magnetURI = "magnet:?xt=urn:btih:6a9759bffd5c0af65319979fb7832189f4f3c35d&dn=sintel.mp4&tr=udp%3A%2F%2Fexodus.desync.com%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.internetwarriors.net%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&tr=wss%3A%2F%2Ftracker.webtorrent.io&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel-1024-surround.mp4"

var parsedTorrent = magnet(magnetURI)

var client = new Tracker(peerId, port, parsedTorrent)

client.scrape()

client.on('scrape', function (data) {
  console.log(data)
})
```

Bundle up `scrape.js` and it's dependencies into a single file called `bundle.js`:

```bash
browserify scrape.js -o bundle.js`
```

`index.html`:

```js
<script src="bundle.js"></script>
```

Open `index.html` in your browser.

**Comment by feross** [comment]
I also added this example to the `bittorrent-tracker` repo: https://github.com/feross/bittorrent-tracker/blob/master/examples/tracker-scrape.md

**Comment by marcu87** [comment]
WOW! Incredible

It works perfect, really thanks!!!!
