### ISSUE TITLE
No callback when destroying websocket client tracker with consummers > 1

### ISSUE THREAD

**Issue by Chocobozzz** [feross/bittorrent-tracker#141]
Hi :)

If consummers > 1, the callback is not fired (https://github.com/feross/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L142).

I don't have the documentation of the [destroy method](https://github.com/feross/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L97) so I don't know if a "normal comportment".

But it seems to be the cause of an issue with `webtorrent`: if you have `add` 2 (or more) torrents of the same tracker and  you want to `remove` one of them the [callback](https://github.com/feross/webtorrent/blob/master/docs/api.md#clientremovetorrentid-function-callback-err-) is not fired.

**Comment by feross** [comment]
Thanks for reporting this. Looks like it is indeed an issue.

**Comment by feross** [comment]
8.0.0

**Comment by Chocobozzz** [comment]
Great, thanks a lot :)
