### ISSUE TITLE
Fastcast tracker 504 error

### ISSUE THREAD

**Issue by jakefb** [feross/bittorrent-tracker#147]
![screenshot from 2016-04-09 10 09 47](https://cloud.githubusercontent.com/assets/6836282/14398833/6090f82c-fe3b-11e5-8977-8dba869f3685.png)

Hi, I have this error with my bittorent-tracker configuration and can't seem to work out what is causing it. The error seems to appear in the log after a while, instead of immediately.

Here is the code for my tracker https://github.com/fastcast/fastcast-tracker. The latest node modules are installed.

Here is the Fastcast nginx config https://gist.github.com/jakefb/900af9a1b99fac3e1ae20d9112bc6e6d

@feross do you know why this could be happening?

**Comment by DiegoRBaquero** [comment]
Problem was this line [nginx.conf#65](https://gist.github.com/jakefb/900af9a1b99fac3e1ae20d9112bc6e6d#file-gistfile1-txt-L65)

I've fixed it in the server and it's now working fine. This can be closed @feross

**Comment by yciabaud** [comment]
Ok thank you for fixing this.

**Comment by feross** [comment]
Cheers!
