### ISSUE TITLE
Double default `numwant` for webrtc trackers (after Chrome 51 is released)

### ISSUE THREAD

**Issue by feross** [feross/bittorrent-tracker#152]
The [limitation on number of peers](https://github.com/feross/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L64) is just a temporary fix until Chrome 51 is released. There's a bad leak on OS X that causes 100% CPU usage. Once that's out, we can bump that number by a factor of 2 or 4, and then the chance that your local peer will be found will be higher.

https://github.com/feross/bittorrent-tracker/blob/master/lib/client/websocket-tracker.js#L64

**Comment by yciabaud** [comment]
Ready to increase that now?

**Comment by feross** [comment]
Yes, let's do it!
