### ISSUE TITLE
udp server: bind EINVAL 0.0.0.0:41234

### ISSUE THREAD

**Issue by pietrovismara** [feross/bittorrent-tracker#153]
Hi,
I got a problem with the udp server. This are my configs: 
```
var server = new Server({
    udp: true, // enable udp server? [default=true]
    http: false, // enable http server? [default=true]
    ws: false, // enable websocket server? [default=true]
    stats: true, // enable web-based statistics? [default=true]
})
```

When i call:
```
server.listen(41234, "0.0.0.0", function() {
    console.log("server listening at 0.0.0.0:41234");
});
```

I get `bind EINVAL 0.0.0.0:41234`, no matter what port i try to use. I even tried on another machine and i get the same error.
Disabling udp and enabling http only works, but i get other errors like
```
Warning: invalid action in HTTP request: /?numwant=50&uploaded=0&downloaded=0&left=&event=started&compact=1&info_hash=%92%83%C6%98%BB%A76%1C%3B%1F%8Fw%97p%A3%DB%97%2379&peer_id=-WW0093-62b7f9b72133&port=37854
```

But maybe this is for another issue.

Anyway can you tell me what am i doing wrong?

**Comment by pietrovismara** [comment]
I found that by just calling `server.listen(port);` it works. That's weird since the readme.md file states that also hostname and callback function can be passed.

**Comment by monyxie** [comment]
I think this is because the server always tries to create sockets for both IPv4 and IPv6, even if you pass a IPv4 address as hostname.

**Comment by feross** [comment]
You can specify different hostnames for each socket type. For example:

```js
server.listen(41234, {
  udp: '0.0.0.0',
  udp6: 'xxxxxx'
}, callback)
```
