### ISSUE TITLE
SSL wss server problem

### ISSUE THREAD

**Issue by yanshekki** [feross/bittorrent-tracker#162]
hi guys,

I have problem that how to build a wss server with bittorrent-tracker?

I am using the https to run website that can't use ws to connect tracker server.

how to do wss with bittorrent-tracker?

thank you!

**Comment by yciabaud** [comment]
Hi @yanshekki, 

bittorrent-tracker does not handle secure connections on its own, most of users are using a reverse proxy like nginx or apache to manage SSL connections.

Maybe you can use your webserver to handle this?

**Comment by yanshekki** [comment]
@yciabaud oh... thank you for your help. I'll try to use apache to do it.

**Comment by yciabaud** [comment]
Yes you should make it work with mod_proxy.

**Comment by PopTudor** [comment]
For further reference to anyone coming here I'll let my "stackoverflow" findings here.  
The library does not tell you any error so I had to look [here](https://github.com/webtorrent/bittorrent-tracker/blob/5b9da4a5e2b4e64471e6b20f645f300cd0258997/client.js#L108) to understand what is going on. From the link, you can see that the only valid protocol to access your HTTPS site is WSS. So https://domain.com or ws://domain.com does not work and it must be **wss://domain.com** (mine looks like this wss://super-transfer.com/ws  ...sorry for the ad :) ).
Next Nginx. Install it with any tutorial on the web. Setup https from [any](https://certbot.eff.org/) tutorial on the web. Last step, inside your `/etc/nginx/sites-available/default` `server{ }` block add the following 
```
location /ws {  
      proxy_pass  http://localhost:8765;  //  bittorrent-tracker server
      proxy_http_version 1.1;  
      proxy_set_header Upgrade $http_upgrade;  
      proxy_set_header Connection "upgrade";  
}
```
Restart nginx `sudo nginx -s reload` for changes to take effect. You are done.
