### ISSUE TITLE
Send same-ip peer first

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/bittorrent-tracker#165]
Idea taken from: https://github.com/feross/webtorrent/issues/67#issuecomment-234012941

If a peer is trying to download the same torrent multiple times, it should connect to itself first to share the pieces locally at full speed.

**Comment by feross** [comment]
In order to implement this, we would need to keep a separate lookup table (js object) that maps ip address to an array of peers on that ip address. But that's a lot of extra bookkeeping to optimize what's basically an edge case. I don't think it's worth making the server do more work it.
