### ISSUE TITLE
"Option `peerId` is required"

### ISSUE THREAD

**Issue by k0nsl** [feross/bittorrent-tracker#166]
Hey,

I got some issue which is probably just an oversight on my part, although I did think [this example](https://github.com/feross/bittorrent-tracker/blob/master/examples/tracker-scrape.md) would work without any issues.

Well, it doesn't work for me. I only added my own magnet link rather than the one already defined. When I browse to `index.html` I see the following in my console:
![alt text](https://screen.img-cdn.ru/2016-07-24_03-02-34.png "console error")

As far as I know `peerId` has this defined: `new Buffer('01234567890123456789')`. The `index.html` file and the corresponding JS can be found here: [https://kebab.host/tracker/](https://kebab.host/tracker/)

Any ideas or help is heartily welcome :D

**Comment by DiegoRBaquero** [comment]
Could you post your JS unbundled? :)

**Comment by feross** [comment]
The code in the example file was out of date. I just updated it so it works with the API changes that were made in the latest version.

**Comment by k0nsl** [comment]
Yes, I believe it's working fine now :)

![alt text](https://screen.img-cdn.ru/chrome_2016-07-27_00-04-40.png "console error")

Thank  you, @feross.
