### ISSUE TITLE
Callback not always called with scrape

### ISSUE THREAD

**Issue by btmdave** [feross/bittorrent-tracker#173]
Taking a look here: https://github.com/feross/bittorrent-tracker/blob/master/client.js#L148

It seems that sometimes this gets hung up and with the check of `len === 0`, resulting in a callback not being sent.   Adding an else `cb(null, results)` seems to work.

**Comment by alxhotel** [comment]
Can you give the steps on how to reproduce this?

**Comment by feross** [comment]
This is expected behavior. If the trackers you're scraping from are down, and no responses are received, then this will just hang. You should use a timeout in your own code.
