### ISSUE TITLE
Realtime torrent import

### ISSUE THREAD

**Issue by darkwolf66** [feross/bittorrent-tracker#174]
Hi, I found myself thinking, it would be possible to take the request to the tracker in real time and the tracker make the request on another tracker, so webtorrent can stream with udp trackers, for example large public trackers udp as desync, coppersurfer?

Sorry for my English.

**Comment by alxhotel** [comment]
That would only work for node clients. And even so, those clients can add any trackers they want; such as udp trackers. So I don't think there's any need for that feature.

**Comment by DiegoRBaquero** [comment]
I understood this as a proxy/relay that allows tracking using other trackers.

I also don't think there's a need for this feature.

**Comment by feross** [comment]
@darkwolf66 Thanks for the suggestion, but this wouldn't really work because trackers aren't used for sending actual torrent data.

They just help peers to connect directly to each other. And there's no way to get a browser to directly connect to a TCP/uTP based desktop torrent client.

**Comment by chovy** [comment]
I think he's getting at making a ws:// tracker available for the web that is a proxy for udp:// on the server side. I'm also wondering how to do this.

**Comment by DiegoRBaquero** [comment]
@chovy It makes no sense to proxy udp:// to wss://, WebSocket trackers are for WebRTC peers, which can't connect to TCP/UDP.

**Comment by darkwolf66** [comment]
I had not thought like a proxy but thinking it would be a proxy, I would have to implement the protocol used in the udp and tcp tracker to convert to wss protocol
