### ISSUE TITLE
SOCKS5 Support

### ISSUE THREAD

**Issue by Miserlou** [feross/bittorrent-tracker#178]
Previous discussion: https://github.com/feross/bittorrent-tracker/issues/22

I've got a working version of SOCKS5 support for [peer-wire-swarm](https://github.com/mafintosh/peer-wire-swarm/issues/20) and plan on adding the same for the communication with the tracker.

From where it stands for this package, it seems like this would actually involve adding adding SOCKS5 support into simple-get using [proxysocket's createAgent](https://github.com/krisives/proxysocket#making-http-requests) and then using that updated interface in this project. Might as well do HTTP proxies with [tunnel](https://github.com/sindresorhus/got#proxies) simultaneously ([related](https://github.com/feross/simple-get/issues/22)).

Acceptable?

**Comment by yciabaud** [comment]
@Miserlou I worked on proxy support in #157, it works with both http and socks5 proxies.
Needs some reviews before merging but it should come.

**Comment by Miserlou** [comment]
Oh, excellent! Okay, that certainly saves me the trouble, well done. 

I've cloned your code and will test my application with it soon. I'll close this ticket and move the discussion to the other thread.. which it looks like I've actually already posted it. I've been chasing my own tail a little bit, it seems..
