### ISSUE TITLE
Impossible connect with ws from browser with express server

### ISSUE THREAD

**Issue by jorma16** [feross/bittorrent-tracker#183]
Hello, I'm trying to connect a browser through websockets to my bittorrent-tracker server integrated in express. With http works fine because I'm doing this:

var onHttpRequest = server.onHttpRequest.bind(server);
app.get('/announce', onHttpRequest);
app.get('/scrape', onHttpRequest);

But with ws is not working, I don't know why but I think because some misconfiguration in the integration with express... What I'm doing bad??

Thanks in advice!

**Comment by jorma16** [comment]
Well... Now I have found the solution, I used express-ws to switch the ws endpoint and redirect to the ws endpoint of the bittorrent tracker. Like the GET endpoints, but with ws.

**Comment by feross** [comment]
Glad you got it figured out
