### ISSUE TITLE
How to use secret key for private trackers

### ISSUE THREAD

**Issue by bertofer** [feross/bittorrent-tracker#184]
In the documentation I can see that:

```
 // It is possible to block by peer id (whitelisting torrent clients) or by secret
 // key (private trackers).
```

I am interested on the secret key, as my project uses a private tracker, but I haven't found any other information on how to use the secret key from the client.

Thanks for the amazing work!

**Comment by feross** [comment]
There's more information about private trackers in the issue where this feature was first discussed: https://github.com/feross/bittorrent-tracker/issues/58
