### ISSUE TITLE
Create a websocket proxy for udp:// trackers?

### ISSUE THREAD

**Issue by chovy** [feross/bittorrent-tracker#189]
Is it possible (looking for example if available) to use bittorrent-tracker to create a websocket tracker that proxies requests to other udp:// trackers?

**Comment by CraigglesO** [comment]
The problem is a tracker protocol is VERY simplistic and requires a specific code response for the client to take it seriously. So I would suggest just setting up a udp address that simply points to another udp address. You don't need a 'tracker' for this I don't believe.

**Comment by chovy** [comment]
Not sure but I think webtorrents only works with websocket trackers in the browser. Since I could only find 3 I was wanting to create a wss:// proxy that connects to the many udp:// trackers out there.

**Comment by feross** [comment]
Browsers can't send UDP packets. So if you're going to have to proxy all the traffic over websocket, why not just add first-class websocket support to the tracker? That's the approach we took in this package.

That's also not the only reason. WebRTC require two-way communication between peers (through the tracker) to set up a connection. So, there's really no way to get a normal UDP tracker to do that for us.

**Comment by chovy** [comment]
@feross there a list of udp trackers here: 

http://coppersurfer.tk/

But they are completley useless with webtorrent since they are not websocket. I am wondering if I can run my own websocket tracker using bittorrent-tracker that then passes the request off to these udp trackers as a proxy. My app using webtorrent would just interface with my websocket server.

Is this possible?

**Comment by feross** [comment]
@chovy You don't need a UDP tracker at all. Just run `bittorrent-tracker` and then make your app use it as the tracker. That's it.

**Comment by chovy** [comment]
Wouldn't my tracker need to connect to other trackers to get information?

**Comment by DiegoRBaquero** [comment]
Wouldn't work. WebRTC peers that use websocket tracker can only connect to WebRTC peers that use that same websocket tracker. You can't give UDP peers info to WebRTC peers.
