### ISSUE TITLE
Can't Start on Linux

### ISSUE THREAD

**Issue by Edward-Stryfe** [feross/bittorrent-tracker#192]
`> bittorrent-tracker@8.1.0 start /home/billy/node_modules/bittorrent-tracker
> node server.js "bittorrent-tracker"

sh: 1: node: not found

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start" "bittorrent-tracker"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! bittorrent-tracker@8.1.0 start: `node server.js "bittorrent-tracker"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the bittorrent-tracker@8.1.0 start script 'node server.js "bittorrent-tracker"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bittorrent-tracker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js "bittorrent-tracker"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bittorrent-tracker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bittorrent-tracker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/billy/node_modules/bittorrent-tracker/npm-debug.log
`

That's the response I get when running `npm start bittorrent-tracker` I made sure to update and upgrade nodejs and npm. What am I doing wrong? It installed just fine. I tried filling in the fields in server.js manually but got the same error. I am in the bittorrent-tracker directory as well.

**Comment by feross** [comment]
On ubuntu, there is no `node` binary because the name was taken by some other project first. So node is installed as `nodejs`. But almost all node scripts assume that `node` will exist. So you need to also `sudo  apt install nodejs-legacy`

**Comment by Edward-Stryfe** [comment]
I installed the legacy version and it gave me some errors cause I had nginx installed so I uninstalled it and all its packages and made sure the legacy version was installed but what do I need to do to compile the binary? Because I'm getting the same errors.

**Comment by feross** [comment]
Installing `nodejs-legacy` should not give you any errors. It literally just installs a symlink from `/usr/bin/node` to `/usr/bin/nodejs` to make scripts that depend on `/usr/bin/node` start working.

I'm not sure what binary you're talking about compiling. You can also just try creating the symlink yourself: `sudo ln -s /usr/bin/nodejs /usr/bin/node`
