### ISSUE TITLE
Inner workings of WS

### ISSUE THREAD

**Issue by CraigglesO** [feross/bittorrent-tracker#195]
I keep trying to capture packets from your webtorrent app. I setup a server that runs at port 80 with a websocket listening...

I can send it packets for testing with a client. But when I use your app, no payload arrives.

Id also like to know if you just use the exact same protocol as udp for start/stop/update/scrape and so on? That would be highly convenient LOL. I'm going to assume you use json though...

**Comment by feross** [comment]
When you use what app?

**Comment by CraigglesO** [comment]
Webtorrent OS X (electron) app Version 0.17.2 (0.97.2)

Sorry, I should have specified this. Should I experiment with this apps client alone first?

It works perfectly UDP, but when I try WS I get no response.

I create a magnet with udp://0.0.0.0:1337 and then separately I try wss://0.0.0.0

**Comment by CraigglesO** [comment]
Astonishingly, Using the client here I get:

`Unsupported tracker protocol: wss://0.0.0.0`

I have to be doing something wrong?

**Comment by Robien** [comment]
I am not sure I understood well your problem but it might be an issue between ws and wss.
wss is websocket secure and it is not natively supported by bittorrent-tracker as it needs ciphering.

You can try ws://localhost instead of wss://

If you really need the secure version you may have to use your web server as a proxy to use ciphering.

**Comment by CraigglesO** [comment]
No, I tried both. I've tried 20 different styles and small differences. None of them work.

**Comment by feross** [comment]
@CraigglesO This is almost certainly an issue with your packet capturing. It works fine for me:

```bash
$ DEBUG=* bittorrent-tracker
HTTP tracker: http://localhost:8000/announce
UDP tracker: udp://0.0.0.0:8000
UDP6 tracker: udp://localhost:8000
WebSocket tracker: ws://localhost:8000
Tracker stats: http://localhost:8000/stats
```

Then start WebTorrent Desktop, create a new torrent, specify "ws://localhost:8000" as the tracker in "Show Advanced Settings...". Then watch the logs come into the tracker.

**Comment by CraigglesO** [comment]
I understand now.

So you use:
```
{
  "complete":0,
  "incomplete":1,
  "action":"announce",
  "interval":120,
  "info_hash":"¿\u0011QÈhJ»¨&`1öªogÖÔ¡¾"
}
```

And the infohash is binary data.

Here is my ultimate question:
Why did use such a drastic overhead for a simple tracker implementation?

You added WebRTC to quickly connect, ask one question, disconnect.

Isn't that overkill? 
Why not just Websockets?

Just curious.

**Comment by feross** [comment]
WebRTC is actually how the **peers** talk to each other. WebSockets are used to talk to **tracker servers**.

**Comment by CraigglesO** [comment]
That's what I figured. I must have misread your code. I'll read through again.

Thanks for your time.

**Comment by CraigglesO** [comment]
ONE last question!!!!

```
received: { numwant: 10,
  uploaded: 0,
  downloaded: 0,
  left: null,
  action: 'announce',
  info_hash: '¿\u0011QÈhJ»¨&`1öªogÖÔ¡¾',
  peer_id: '-WD0017-2oKzxV88MwHE',
  offers: 
   [ { offer: [Object], offer_id: 'Ixÿ1fF³ØÅ÷n\u001bVZixPå' },
     { offer: [Object],
       offer_id: '\u0002([[wÓcÁ¦\u0002HÔ£Óø¸\n0\n' },
     { offer: [Object],
       offer_id: '\t½>\u001am)§\u0019¹J½Ä\u0006³¨!' },
     { offer: [Object], offer_id: 'Áð,NÂ13uXö\u0016 }E5}D' },
     { offer: [Object], offer_id: '·ä\u0014@Õ°]W|,·2a! Ô5' },
     { offer: [Object], offer_id: '-§DYOr%\u0013üHÉm\u0016!{WT' },
     { offer: [Object],
       offer_id: 'óöý(\u0014Ò_\'¯²w)\u0012Ý×\b\u001d' },
     { offer: [Object], offer_id: 'KÂ\fIyÿÐC­/Å2#tm.eá§' },
     { offer: [Object],
       offer_id: 'É¨\u0013o±×.¢\u0015\u0004#µI:' },
     { offer: [Object],
       offer_id: 'üéø²_:\u0015\u001a»\u00062r\u0016Yá*7' } ] }
```


What does numwant mean? The number of offers that will be sent? And why are you storing offers in the tracker? Couldn't this be handled directly between the peers?

**Comment by feross** [comment]
You should read about how WebRTC connections work. Specifically, WebRTC signaling. Here's a good article: https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

In short, the offers and answers are used to help peers connect to each other. They must be passed through the tracker in order to help the peers get connected.
