### ISSUE TITLE
incomplete + complete != # of peers

### ISSUE THREAD

**Issue by DiegoRBaquero** [feross/bittorrent-tracker#196]
There's an inconsistency.

It grows with time.

**Comment by feross** [comment]
Are you running just a ws tracker, or the other ones too? If it's just ws, this would help to narrow the issue down.

**Comment by DiegoRBaquero** [comment]
Just a ws (uwt). FastCast and OpenWebTorrent (bittorrent-tracker) trackers have the issue too, both ws only too.

**Comment by feross** [comment]
Can you share the code you're using to check the various counts?

**Comment by DiegoRBaquero** [comment]
I didn't really use code.

The first initial message from tracker.btorrent.xyz for Sintel torrent is:

```json
{"complete":1070,"incomplete":17821,"action":"announce","interval":120,"info_hash":"jY¿ý\\\nöS\u0019·!ôóÃ]"}
```

The tracker doesn't even have that many connected peers. Torrent has 127 peers right now.

FastCast's:

```json
{"complete":2418,"incomplete":46529,"action":"announce","interval":120,"info_hash":"jY¿ý\\\nöS\u0019·!ôóÃ]"}
```

OpenWebTorrent's:
```json
{"complete":6163,"incomplete":136759,"action":"announce","interval":120,"info_hash":"jY¿ý\\\nöS\u0019·!ôóÃ]"}
```

**Comment by feross** [comment]
@DiegoRBaquero I took a stab at fixing this. See here: https://github.com/feross/bittorrent-tracker/pull/198 Can you see if this fixes your problem?
