### ISSUE TITLE
example of testing tracker with wscat?

### ISSUE THREAD

**Issue by chovy** [feross/bittorrent-tracker#214]
I can connect to my tracker: `wscat -c wss://example.com/tracker`
but I'm not sure what to type test that this is working.

Anything I type gives a JSON parser error.

**Comment by DiegoRBaquero** [comment]
First packet sent:

```
{"numwant":10,"uploaded":0,"downloaded":0,"left":16958,"event":"started","action":"announce","info_hash":"laÔÈ(ôêX!G±0«`ÂÕ\u000fÎ","peer_id":"-WW0098-+GzLT/7SGhze","offers":[]}	
```

Notice the binary stuff.

You won't be able to do anything through wscat to be honest.

**Comment by feross** [comment]
Closing, as this is not an issue with `bittorrent-tracker`. Feel free to continue discussion.
