### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by davy39** [feross/bittorrent-tracker#22]
Hi,

My ISP is blocking my announces to tracker's http and udp... After a quick read of the code, it looks like bittorent-tracker would be the first one to be updated in order to support poxies.

Would it be possible to modify requestHttp and requestUdp for them to use proxy options that could be set in opts ?
Like in libtorrent-rasterbar, those options could be type(http,https, sock4, sock5), hostname, port, username and password.
Of course, requestUdp will only use sock5 proxies.

Thank you very much for your work !

**Comment by feross** [comment]
This issue is stale. Feel free to open a new issue if you want proxy support.
