### ISSUE TITLE
Callback at the end of scraping process

### ISSUE THREAD

**Issue by elhorla** [feross/bittorrent-tracker#221]
Hi feross !

How i can call a callback function when the scraping process is terminated ?
-------------------------------------------------------------------------------------------------------------------
As default is there a max timeout during the scraping process ? ( If the trackers not respond for example )

Thanks , You have done an incredible job !
PS : Sorry for my bad english , i'm french

**Comment by elhorla** [comment]
Please answer me

**Comment by feross** [comment]
You need to create your own timer using `setTimeout`, since there's no way to determine whether a tracker is being super slow, or if it's down entirely and will never send a response.

**Comment by elhorla** [comment]
Ok thanks for this response
