### ISSUE TITLE
Performance concerns

### ISSUE THREAD

**Issue by coldwinds** [feross/bittorrent-tracker#25]
Is there any benchmark between the opentracker in C ( http://en.wikipedia.org/wiki/Opentracker ) and this tracker in nodejs?

I'd like to learn about it's performance. Is it capable to support a very large tracker site? like publicbt

**Comment by feross** [comment]
I've heard somewhere (anecdotally) that a user was able to get near 1 million concurrent users using the UDP tracker (disabling HTTP and WebSocket). That's way better than I expected, though nowhere near what something like OpenTracker can get.

I'm personally not interested in trying to make this package compete with hand-optimized C (it's probably not possible). But PRs that improve performance are always welcome!
