### ISSUE TITLE
Improve announce interface

### ISSUE THREAD

**Issue by feross** [feross/bittorrent-tracker#3]
Currently setIntervals happen inside this package, but it has no way to know what upload/download numbers to report to the tracker.

Perhaps this should just be the responsibility of the user? There's already a `client.update()` function.

**Comment by yciabaud** [comment]
In my opinion we can allow the user to provide a callback to update the data when setInterval is triggered.

I can send you a PR in that way.

**Comment by feross** [comment]
Fixed by #107 and released as 7.3.0.
