### ISSUE TITLE
[Req] configurable query path for /announce & /scrape and more options

### ISSUE THREAD

**Issue by coldwinds** [feross/bittorrent-tracker#35]
I found it's hardcoded in server.js

> if (s[0] === '/announce') {
> ..
> } else if (s[0] === '/scrape') {
> ..
> error('only /announce and /scrape are valid endpoints')

I think it will be more flexible let user to config the announce path such as to '/', and optionally disable scrapping.

**Comment by feross** [comment]
It is possible to set custom paths using the technique described in https://github.com/feross/bittorrent-tracker/issues/58#issuecomment-72343349, and since there's been no PR to support this feature more explicitly, I'm gonna close this issue.

PR still welcome.
