### ISSUE TITLE
Tracker server should prune old peers who did not leave the swarm gracefully

### ISSUE THREAD

**Issue by feross** [feross/bittorrent-tracker#4]
If a peer doesn't send a `stop` message then we should prune them after a while.

**Comment by feross** [comment]
This is the package we should use: https://npmjs.com/package/lru

It's also used in `bittorrent-dht` where it works great.

**Comment by dkobia** [comment]
@feross, glad to see even a little progress on this ticket

**Comment by DiegoRBaquero** [comment]
IMO we should use a TTL based cached as LRU depends on a size

**Comment by DiegoRBaquero** [comment]
I'm thinking of throwing a PR based on node-cache as @lorentzkim did in  https://github.com/feross/bittorrent-tracker/pull/87. The module doesn't create n timers/intervals, but I think all of its code is synchronous, especially the periodic TTL check that removes old keys.

I've created an issue on its repo and plan to PR to fix the issue. (https://github.com/tcs-de/nodecache/issues/56)

Thoughts?

**Comment by feross** [comment]
I know the tracker spec technically requires an lru based on time, but space is the actual real constraint. If a tracker gets popular, it shouldn't crash with an out-of-memory error -- it should just drop drop peers sooner than normal.

An lru that depends on size is close enough to right. The worst that happens is that on an unpopular tracker, old ip addresses will be given out. But that already happens all the time and clients don't mind.

**Comment by yciabaud** [comment]
If we use `lru` what would be the default length of the cache? 10K like `bittorrent-dht`?
Do we use `maxAge` option too in order to fit the tracker spec?

**Comment by feross** [comment]
I think we should try to do what the spec says by default, but of course let the user set the lru options themselves if they want to.

The `lru` readme says: "If you pass `maxAge` items will be evicted if they are older than `maxAge` when you access them." Let's make sure that items that never get accessed don't stick around forever. If that will happen with `maxAge`, then I'd rather just set `max` (i.e. max elements to store) instead.

**Comment by yciabaud** [comment]
I was thinking of setting both params, `max` to ensure we are not consuming too much memory and `maxAge` to avoid returning peers that did not leave gracefully on announce if the `max` is not reached.

The downside of this is that if we use `maxAge` is that we need to handle when we try to access an old peer and each access will bring the peer to the top so `max` can drop a more active peer.

Do you think returning old peers is no big deal? Using `max` only would be easier.

**Comment by yciabaud** [comment]
My PR is ready, I am using both rules to fit both needs, please tell me what you think.

**Comment by DiegoRBaquero** [comment]
The only issue case I see is when a peer doesn't leave gracefully and the tracker never tries to get it from LRU (No more peers ever request peers from an infoHash), it would never get evicted.

I left some comments in your PR @yciabaud

**Comment by yciabaud** [comment]
You are right, for those I cannot see how to solve it. Maybe with another lru on torrents, and checking the tail to prune not requested torrent.

**Comment by yciabaud** [comment]
Fixed in #160
