### ISSUE TITLE
whitelist/filtering of torrent info hashes

### ISSUE THREAD

**Issue by pwmckenna** [feross/bittorrent-tracker#44]
It would be nice to be able to dynamically control which torrents the tracker tracks...maybe with an api like below?

```js
var Server = require('bittorrent-tracker').Server

var server = new Server({
  udp: true, // enable udp server? [default=true]
  http: true // enable http server? [default=true]
  filter: function (hash) {
    return hash === 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
  }
});

```

**Comment by feross** [comment]
Implemented in #57 and released as [3.0.0](https://github.com/feross/bittorrent-tracker/commit/82e6792a6bc4d1d608d89988ce7fa0ba5f001ffc).
