### ISSUE TITLE
info_hash and peer_id is coming encrypted

### ISSUE THREAD

**Issue by parth1729** [feross/bittorrent-tracker#54]
We are planning to use bittorrent-tracker and extend functionality to save torrent details and user  details in mongodb database.

However, when we are checking peer_id and info_hash it is giving improper values. It looks like either those values are garbled  or encrypted. 

info_hash and peer_id are specified here http://23.102.65.126:81/Capture.png

**Comment by astro** [comment]
Do you run the latest version of all modules? As of #47 both info_hash and peer_id are now handled as hexadecimal, no longer binary strings which can break.

**Comment by feross** [comment]
@parth1729 What @astro said is correct. If you share your code, we help you debug further.

**Comment by parth1729** [comment]
Thnaks @astro and @feross , I am integrating the code and debugging it . I will inform you if more information is required. Thanks for quick support.

**Comment by Mochaka** [comment]
@parth1729 sorry to comment on a closed ticket, but would you be able to share your code for saving the info in mongodb?

Thanks

**Comment by parth1729** [comment]
Aaron, I stuck in some other work in between so i could not take this
further with proper saving of data in mongodb.I have been using mongoose
and trying to dump data from swarm object. However, this is not complete
yet. I will inform you once it is done. I am planning to resume again on
this next week.

On Fri, Feb 13, 2015 at 12:54 PM, Aaron Florey <notifications@github.com>
wrote:

> @parth1729 <https://github.com/parth1729> sorry to comment on a closed
> ticket, but would you be able to share your code for saving the info in
> mongodb?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/feross/bittorrent-tracker/issues/54#issuecomment-74214959>
> .
>



-- 
Regards,
Parth R. Pandya,

**Comment by Mochaka** [comment]
@parth1729 Alright thanks, i'm also working on the same thing. Got everything saved to Redis atm.
