### ISSUE TITLE
Private Tracker Functionality

### ISSUE THREAD

**Issue by KamuelaFranco** [feross/bittorrent-tracker#58]
What work can be done to this tracker to allow for private functionality?

**Comment by astro** [comment]
Private torrents is a bit in the .torrent files, to be respected by clients. Please see [the BEP](http://www.bittorrent.org/beps/bep_0027.html).

**Comment by KamuelaFranco** [comment]
What about .torrent files that need to pass authentication with the tracker? I was told this is sometimes accomplished through specific announce URL's. How does this project allow for this level of user authorization?

**Comment by astro** [comment]
I currently do it like in the express example but with a custom handler that checks these URLs. I then prepare `req.url = "/announce"` and pass to `onHttpRequest()`. Admittedly a little quirky.

Actually, I would like to move the checks to my `Swarm` implementation. For that we'll need to:
- [ ] Convey the HTTP req and its parameters to Swarm params
- [ ] expose interfaces that let us do our own req.url checks

**Comment by KamuelaFranco** [comment]
Can you give me an example of your current workaround? Would you keep these announce ID's in a database?

**Comment by astro** [comment]
My express handler looks like this:
```js
app.get('/tracker/:secret/announce', function (req, res) {
    checkSecret(req.params.secret, function (isValid) {
        if (isValid) {
            req.url = "/announce";
            server.onHttpRequest(req, res);
        } else {
            res.send(200, EMPTY_ANNOUNCE_RESPONSE);
        }
    });
});
```
As I said: there would be a better way.

Regarding what/how to store the Swarm data: it depends on your use-case. You will need to keep peer_id in addition to host/port for non-compact tracker responses. (Though you could probably make them up and clients will still connect to the peers.)

**Comment by feross** [comment]
> expose interfaces that let us do our own req.url checks

That would also address this issue: https://github.com/feross/bittorrent-tracker/issues/35

**Comment by feross** [comment]
Answering @KamuelaFranco's email question here for posterity:

> Does your tracker already monitor peer statistics? E.g. uploaded amounts, downloaded amounts, etc? If so, the only change would be through the Express implementation portion in your example.

The tracker doesn't track this kind of information for individual peers, but it passes it when it calls swarm.announce() on your custom Swarm backend, so you can track it there :)

**Comment by astro** [comment]
PR #59 has been closed.
