### ISSUE TITLE
Passing params back from onHttpRequest Function

### ISSUE THREAD

**Issue by KamuelaFranco** [feross/bittorrent-tracker#61]
Can this be achieved asynchronously? Perhaps as a prototype for onHttpRequest that includes a callback function? Or is there a better way?

**Comment by feross** [comment]
I don't understand what you mean by "pass params back from onHttpRequest". What are you trying to do?

**Comment by feross** [comment]
Closing this because I don't understand what's being asked for. If there's more detail provided, we can re-open this.
