### ISSUE TITLE
Negative amount of leechers

### ISSUE THREAD

**Issue by stylesuxx** [feross/bittorrent-tracker#65]
Hey guys,
On some of the torrents on my tracker I see a negative amount of leechers. This seems to happen on torrents where one or more clients already have the files when adding a torrent, means:

    (amount of seeders) = (amount of leechers) * -1 

As soon as a new leecher joins the pool, the amount of leechers goes up, but is still not correct then (at least on those torrents with negative leecher count).

My torrent object looks like so in the moment:

    '55600bbcb00fd923dee589655f74900f5abxxxx': { peers: [Object], complete: 2, incomplete: -2 },
     fe0a979f104964e69e8bbc8bcff5bde120d2xxxx: { peers: [Object], complete: 2, incomplete: -1 },
     d3939d09f0a259c5be1cd31cd06499901ca2xxxx: { peers: [Object], complete: 1, incomplete: 0 },

The first torrent has two seeders and no leecher in reality. The Second torrent has two seeders and one leecher. The third torrent seems to be all right, one seeder, no negative leecher and no leecher at all.

Any ideas on this?

**Comment by feross** [comment]
It would help if you restarted the tracker from scratch, but this time run it with the environment variable `DEBUG=bittorrent-tracker` and share the output.

Example: `DEBUG=bittorrent-tracker node my-tracker.js`

Thanks!

**Comment by feross** [comment]
I believe I've fixed this issue in v3.4.4. If you still encounter this issue, please leave a comment or open a new issue.

**Comment by feross** [comment]
Attempted a different fix for "Error: value is out of bounds" that should be a more permanent fix. Let me know if you see that error again.

Released as 3.6.3.
