### ISSUE TITLE
Problem  with adding torrent file to announce 

### ISSUE THREAD

**Issue by smagikern** [feross/bittorrent-tracker#66]
How i can add { register } torrent file to tracker. 

I need solution that track new torrent file if i add announce url to newly created torrent

Something like tracker.announce() in   Java library https://github.com/mpetazzoni/ttorrent

**Comment by feross** [comment]
The tracker will track any torrent that gets announced to it. No need to explicitly tell the tracker which torrents to track.

**Comment by smagikern** [comment]
I succesful setup bittorrent-tracker? but get following error:
bittorrent-trackerbittorrent-tracker: command not found
May be i must start javascript server first? How?
Date: Thu, 26 Mar 2015 17:03:14 -0700

**Comment by feross** [comment]
After you `npm install bittorrent-tracker -g`, a `bittorrent-tracker` command should get installed to wherever npm installs your global packages (you can find out where with `npm bin -g`). Make sure that this location is in your PATH. Then the command should be available to you.

**Comment by smagikern** [comment]
bittorrent-trackerOk it work. But what is announce url ? I try this http://52.11.183.14/media/announce:8000
Date: Thu, 9 Apr 2015 16:04:37 -0700

**Comment by smagikern** [comment]
Previous question i found that not installed sudo apt-get install nodejs-legacyIn summer 2012 Debian maintainers decided to rename Node.js executable to prevent some kind of namespace collision with another package.
Date: Thu, 9 Apr 2015 16:04:37 -0700
