### ISSUE TITLE
Additional information sent over an announce

### ISSUE THREAD

**Issue by aristeia** [feross/bittorrent-tracker#70]
I would like to run a tracker than can track additional torrent information (its name, etc.) rather than just its infohash. Looking over the source code for UDP requests and parsing them, I cannot find a straightforward way to just add an additional option to the UDP message, and have it converted to a string by the server. Where in the source code would you recommend that I check?

**Comment by feross** [comment]
What is your goal in doing this? You can't necessarily trust the names that your clients provide. What is your plan if multiple clients report different names?

If your goal is to just find out what torrents are being tracked by the tracker, you can get access to the list of infohashes that are being tracked by the tracker. Then you can look up information about these infohashes by downloading the torrent metadata directly from the swarm, or using a third-party lookup API.
