### ISSUE TITLE
Error: value is out of bounds

### ISSUE THREAD

**Issue by dtrackd** [feross/bittorrent-tracker#72]
First of all, thank you so much for your awesome activity on the tracker project I want to start using this software for an open tracker project we have going which is getting a ton of traffic

Here is the current error I am getting after running the tracker for ~1min:

```
root@box:~# bittorrent-tracker -p 80 -q

/usr/lib/node_modules/bittorrent-tracker/lib/swarm.js:0
(function (exports, require, module, __filename, __dirname) { module.exports =
^
RangeError: Maximum call stack size exceeded
```

Also at some I get this:

```
root@box:~# bittorrent-tracker -p 80 -q

buffer.js:705
    throw TypeError('value is out of bounds');
    ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt32BE (buffer.js:748:5)
    at Object.toUInt32 (/usr/lib/node_modules/bittorrent-tracker/lib/common-node.js:29:7)
    at makeUdpPacket (/usr/lib/node_modules/bittorrent-tracker/server.js:435:16)
    at /usr/lib/node_modules/bittorrent-tracker/server.js:222:15
    at /usr/lib/node_modules/bittorrent-tracker/server.js:374:5
    at Swarm.announce (/usr/lib/node_modules/bittorrent-tracker/lib/swarm.js:24:5)
    at Server._onAnnounce (/usr/lib/node_modules/bittorrent-tracker/server.js:342:9)
    at Server._onRequest (/usr/lib/node_modules/bittorrent-tracker/server.js:329:10)
```

Please do let me know if there is anything more I can do to help debug these issues

Thanks

**Comment by feross** [comment]
How much traffic are you sending to the tracker? I've never seen these errors before.

I just put in a check to prevent the second error (released as 3.5.1), but I can't figure out the first error.

**Comment by dtrackd** [comment]
The testing I am currently going through is around 1 million odd peers. But for production I am truly hoping the tracker will handle ~40 times that.

Currently using OpenTracker (https://erdgeist.org/arts/software/opentracker/) but its reaching points where its blocking and rejecting peers on a single machine. Kinda hoping this would be better.

**Comment by dtrackd** [comment]
Also getting the same error at slightly different position now.

```

buffer.js:705
    throw TypeError('value is out of bounds');
    ^
TypeError: value is out of bounds
    at TypeError (<anonymous>)
    at checkInt (buffer.js:705:11)
    at Buffer.writeUInt32BE (buffer.js:748:5)
    at Object.toUInt32 (/usr/lib/node_modules/bittorrent-tracker/lib/common-node.js:32:7)
    at makeUdpPacket (/usr/lib/node_modules/bittorrent-tracker/server.js:435:16)
    at /usr/lib/node_modules/bittorrent-tracker/server.js:222:15
    at /usr/lib/node_modules/bittorrent-tracker/server.js:374:5
    at Swarm.announce (/usr/lib/node_modules/bittorrent-tracker/lib/swarm.js:24:5)
    at Server._onAnnounce (/usr/lib/node_modules/bittorrent-tracker/server.js:342:9)
    at Server._onRequest (/usr/lib/node_modules/bittorrent-tracker/server.js:329:10)
```

**Comment by feross** [comment]
How are you testing with so many peers? Can you share your script? We should add a benchmark program to this repo so we have a way to measure progress and make sure all changes either improve or don't affect performance.

Doing 40 million peers would be quite an achievement.

**Comment by dtrackd** [comment]
@feross Not using a script. this is real world traffic. We run 2 trackers, one far bigger than the other.
We are using the smaller one to testing this tracker application.

I will be more than happy to share the server's details if it will help you debug more the application while its under constant use feel free to email me at ``track (_at_) demonii.com``

**Comment by feross** [comment]
Attempted a different fix for "Error: value is out of bounds" that should be a more permanent fix. Let me know if you see that error again.

**Comment by dtrackd** [comment]
Thank you for the amazingly quick replies.

I have not gotten any more "out of bounds" errors. how ever now I am getting a few ``RangeError: Maximum call stack size exceeded`` instead. 
Is this an issue on my debain box? is there any limits or some configs I need to raise on the OS level in order to eliminate these? 

Thanks again here are the different errors I have been getting:

```
root@box:~# bittorrent-tracker -p 80 -q

/usr/lib/node_modules/bittorrent-tracker/server.js:403
    return function (cb) {
                    ^
RangeError: Maximum call stack size exceeded
```
```
root@box:~# bittorrent-tracker -p 80 -q

/usr/lib/node_modules/bittorrent-tracker/server.js:404
      swarm.scrape(params, function (err, scrapeInfo) {
                                    ^
RangeError: Maximum call stack size exceeded
```
```
root@box:~# bittorrent-tracker -p 80 -q

/usr/lib/node_modules/bittorrent-tracker/lib/swarm.js:0
(function (exports, require, module, __filename, __dirname) { module.exports =
^
RangeError: Maximum call stack size exceeded
```
