### ISSUE TITLE
Feature: Statistics

### ISSUE THREAD

**Issue by dtrackd** [feross/bittorrent-tracker#74]
A feature request.

Would love to see some form of statistics from this tracker.
I assume some HTTP endpoint (unrelated to if --http is true or false) return JSON would be best.

Stats that I would personally love to see:

* Total Peers count (separated on IPv4 and IPv6 peers)
* Total Seeds count (separated on IPv4 and IPv6 seeds)
* Total Torrent count 
* Connections per min (separated on IPv4 and IPv6 connections)
* Scrapes per min (separated on IPv4 and IPv6 Scrapes)

Just a thought, would be pretty awesome if the tracker operator can display these sort of stats graphed over time.

**Comment by feross** [comment]
Agreed. I've been meaning to add a `/stats` endpoint with this type of info.

**Comment by DiegoRBaquero** [comment]
I've been working on this for BTorrent's tracker: https://tracker.btorrent.xyz/stats

What do you guys think?

**Comment by feross** [comment]
Looks good to me. Want to send a PR? There should be a `stats` option to disable this, though.

**Comment by DiegoRBaquero** [comment]
I have cleaned up things a little bit more: https://tracker.btorrent.xyz/stats

Anything else before starting the PR?

@dtrackd @feross

**Comment by feross** [comment]
@DiegoRBaquero Looks great to me. Send a PR!
