### ISSUE TITLE
Don't return if not listening (websockets)

### ISSUE THREAD

**Issue by Chocobozzz** [feross/bittorrent-tracker#79]
First of all, thanks for you amazing job :)

I noticed one issue with this line: https://github.com/feross/bittorrent-tracker/blob/master/server.js#L302

I run *bittorent-tracker* in an *express* application with the *ws* module and I use `onWebSocketConnection` to redirect *ws* request to the bittorent-tracker server. So the tracker never listens, and thus it returns at this line. If I remove it, all work as expected.

**Comment by feross** [comment]
Thanks for pointing this out. Released as 4.4.5.

**Comment by Chocobozzz** [comment]
Great thanks :)
