### ISSUE TITLE
Async filter function (to interface with database)

### ISSUE THREAD

**Issue by lorentzkim** [feross/bittorrent-tracker#80]
This is from tracker's point of view. 

I am attempting to extend the usage of filter function by e.g. using a database to query whether the torrent has valid infoHash or not, as well as any other params that needs to be checked.

Database queries, as being network requests, are async in nature, and they don't return a value but a callback to do further processing.

Filter function requires a return value (a boolean).

Is there any way that you can think of to easily do both? As I can see it, there's no way to do this cleanly. Using async module or whatnot isn't going to cut it as it's not the order of the processing, but rather inability to return a value from a callback to original caller (which doesn't make sense anyway).

**Comment by feross** [comment]
You're correct, this isn't possible right now since `filter` has to be a sync function. I know that @astro was using this module to interface with a database.

@astro - any ideas about how to accomplish this?

If we must, I suppose we can make the `getSwarm` function asynchronous, but I'd like to avoid that if we can.

**Comment by lorentzkim** [comment]
I've in meanwhile used a module called `deasync` to force everything into a sync, which is a bit of a hack, but works for now. Hopefully there's a good resolution. I can totally understand not wanting to change `getSwarm` though.

**Comment by feross** [comment]
@lorentzkim If you really need this feature, you could send in a PR. I'm willing to consider making `getSwarm` async, but we'll need to bump the major version since folks may be depending on that.

I don't think `getSwarm` is used in that many places, so this might not be too hard of a change.

**Comment by lorentzkim** [comment]
I'll consider doing that.

Do you mind if async module gets added in as a dependency?

**Comment by lorentzkim** [comment]
Don't mind the async thing, looks like you're using run-series and that does about the same for this purpose.

**Comment by feross** [comment]
Yeah, `run-series` is equivalent to `async.series` without all the other cruft.

**Comment by feross** [comment]
@lorentzkim any progress? I'm happy to take a look at an in-progress PR for this and share my feedback.

**Comment by lorentzkim** [comment]
Please see my asnyc_getswarm branch. I was last changing out server.js:444.

**Comment by lorentzkim** [comment]
Rudimentary changes should be done now. Take a look.

**Comment by lorentzkim** [comment]
I am feeling a little iffy about the whole filters and the callback value; perhaps expand the result value to have more meaning than true/false? It already returns err for errors, if there are any. Custom filter reasons perhaps that gets passed to the server correctly?

Might also make sense to drop the infoHash+params thing to just params, since the function signatures are changing anyhow.

**Comment by feross** [comment]
Released as 5.0.0.

**Comment by lorentzkim** [comment]
Stunning work, thanks!

**Comment by feross** [comment]
No problemo!
