### ISSUE TITLE
Expose addr instead of param on complete/update/stop

### ISSUE THREAD

**Issue by lorentzkim** [feross/bittorrent-tracker#81]
Instead of only exposing addr, I think it'd be more flexible to expose the entire params (at `server.js:225`, line that does `self.emit(common.EVENT_NAMES[params.event], params.addr)`) so you can do more intricate processing.

Specifically, peer_id and announce url would be exposed rather than addr alone, and would make handling individual downloaders and torrents a lot neater for applications that need that level of complexity.

I am aware of this possibly breaking API since other modules rely on it; is there a decent solution to expose it?

**Comment by feross** [comment]
We can expose it as a second argument on the events:

```js
server.on('update', function (addr, params) {

})
```

Released as version 4.5.0.
