### ISSUE TITLE
Can I create a bootstrap servers using this tracker module

### ISSUE THREAD

**Issue by vairabagni** [feross/bittorrent-tracker#83]
I wanted to host my own bootstrapping node similar to router.bittorrent.com:6881, router.utorrent.com:6881 or dht.transmissionbt.com:6881.
Is it possible to create it using your bittorrent-tracker module?

**Comment by feross** [comment]
No, those are DHT bootstrap servers, not torrent trackers. You can use the [bittorrent-dht](https://github.com/feross/bittorrent-dht) module for that purpose, though it's not as optimized for the usecase of a bootstrap server as something like https://github.com/jech/dht-bootstrap or https://github.com/bittorrent/bootstrap-dht

**Comment by vairabagni** [comment]
thanks a lot
