### ISSUE TITLE
Running a tracker on raspberry pi

### ISSUE THREAD

**Issue by vairabagni** [feross/bittorrent-tracker#84]
When I execute the following command:
```
pi@raspberrypi ~/dht-tracker/node_modules/.bin $ ./bittorrent-tracker -p 6881
```

it throws:

ERROR: bind EAFNOSUPPORT
ERROR: listen EAFNOSUPPORT

But in windows it is running fine.

**Comment by feross** [comment]
I bet the raspberry pi you're using doesn't support IPv6. If you use UDP, then we attempt to create a UDP6 socket. To confirm, please run:

```
bittorrent-tracker -p 6881 --udp false
```

And let me know if that works without a crash. If so, I think we can make a change so that failure to bind a UDP6 socket isn't fatal.

**Comment by feross** [comment]
Also, you should try updating to the latest version of node. According to https://github.com/joyent/node/issues/8094 it may be a node issue.

**Comment by vairabagni** [comment]
I had to enable ipv6 on my raspbian because without activating udp means by using only http, the tracker was not getting any events (start, update, complete, etc). That is the tracker is not getting info about the torrent itself. 

Anyways after enabling ipv6 on my raspberry and by using both http & udp it is working fine as expected.
