### ISSUE TITLE
onFilter returning error details rather than global "disallowed info_hash"

### ISSUE THREAD

**Issue by lorentzkim** [feross/bittorrent-tracker#85]
Since filter function has become async and receives a callback, perhaps it'll be good to have functionality for standard callback(err, res) form which allows for errors to be passed through, for customised error reasons.

It'll be more usable than just having "disallowed info_hash" for every reason for failure.

**Comment by feross** [comment]
I was trying to make the interface like [`Array.prototype.filter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) as much as possible.

I agree, it would be nice to have a way to specify a message. But the standard `callback(err, res)` interface doesn't make much sense. What is `res`?

We could do just `callback(err)`. If `err == null`, then it's allowed. If `err` is truthy, then it's disallowed and if `err instanceof Error` then the custom error message will be used. But this is another API change...

**Comment by feross** [comment]
Okay, I found a solution I like. It's not a breaking API change.

In addition to returning a boolean (`true` for allowed, `false` for disallowed), you can return an `Error` object to disallow and provide a custom reason.

Released as 5.1.0.

**Comment by lorentzkim** [comment]
Thank you! That solution works.

My reference to err/res was about this: http://thenodeway.io/posts/understanding-error-first-callbacks/

I thought it was convention that async functions return function(err, res), where err is the error object (if exists, null otherwise), and res for result, whatever it may be.
