### ISSUE TITLE
About how announce interval works and should work ?

### ISSUE THREAD

**Issue by chetandhembre** [feross/bittorrent-tracker#86]
Hi, 

I went through [UDP Tracker protocol](http://www.bittorrent.org/beps/bep_0015.html). And found that announce request return `interval` after which peer should announce itself.
So my question is , will reannouncing after `interval` will have same announce parameter (event, downloaded, left, uploaded) as last announce (in which response i received interval as response). Or reannounce will have changed (current event or downloaded count) parameter ? 

Sorry it is not related specifically to this project. But I am not finding answer for this questions.

Do you know any active community where I can ask this type of question ?

Thanks

**Comment by feross** [comment]
You should always send the latest downloaded, left, and uploaded parameters when you do an announce. I recommend checking the `##bittorrent` channel on IRC (freenode) if you need help with this kind of stuff.
