### ISSUE TITLE
Specifying new client IDs

### ISSUE THREAD

**Issue by VoR0220** [feross/bittorrent-tracker#90]
Hi there,

I have a question regarding the robustness of this implementation. If I go ahead and ask it to only allow from what has been an undefined client (a new bittorrent client), if I just input it into the whitelist, will it still hold up? Thanks in advance. Let me know.

**Comment by feross** [comment]
I'm not sure I understand your question.

If you add a filter function that decides whether to respond to clients based on the peer id they report, that will work forever. If some future client decides to start spoofing your client's peer id prefix, then your filter function will allow them in.

This has nothing to do with the robustness of this package's implementation and everything to do with the robustness of your filter function. You'll need to get a bit more clever if that's what you're concerned about.

**Comment by VoR0220** [comment]
My question is moreso in regards to what happens with the client's peer id prefix if it is not recognized? Will I still be able to use this if I configure all the nodes myself?

**Comment by feross** [comment]
This package doesn't check peer ids. If you write a `filter` function, it's up to you to decide what to do if you don't recognize the peer id prefix.

**Comment by VoR0220** [comment]
Awesome. Thanks for the input.
