### ISSUE TITLE
Pluggable DB interface

### ISSUE THREAD

**Issue by FLYBYME** [feross/bittorrent-tracker#95]
I think the code should be more asynchronous when it comes to the methods getSwarm and createSwam. They should take a callback so you can query a DB for peers. Having a million+ torrents in memory just wont work. An upside is persistency.

Any thought on this?

If not Im going to have to fork and refactor the code for my use.

**Comment by FLYBYME** [comment]
Nobody? Nothing? Am I wrong thinking this?

**Comment by feross** [comment]
This request has come up before, I believe.

@astro - do you have any thoughts about this?

**Comment by astro** [comment]
Totally right.

**Comment by feross** [comment]
Sounds like we need to make `getSwarm` and `createSwarm` async.

**Comment by RaulTsc** [comment]
Would you like to change the API or add the async methods aswell?

**Comment by RaulTsc** [comment]
I've submitted a PR, please let me know what you think.

**Comment by feross** [comment]
Let comments on your PR.

**Comment by feross** [comment]
This is done, released as 7.0.0.
